### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by davidmyersdev** [davidmyersdev/octo#232]
It would be nice to have fuzzy searching by default. Currently, Octo supports substring and regex matching.

**Comment by voracious** [comment]
This library might be useful: https://github.com/nextapps-de/flexsearch

**Comment by davidmyersdev** [comment]
Fuzzy search has been implemented for the Assistant feature already. Use or extend this implementation.
https://github.com/davidmyersdev/octo/blob/daf7fe324033d24b28bea5d66c17bb1815760f50/composables/useSearch.ts
