### ISSUE TITLE
Magic link sign in not working for new user

### ISSUE THREAD

**Issue by maggiehenry** [davidmyersdev/octo#257]
Hey all, excited to try the app, but magic link sign in doesn't work.

I signed up for Octo free access at https://octo.app/product/pricing:
<img width="473" alt="Screenshot 2023-10-25 at 12 37 41 PM" src="https://github.com/davidmyersdev/octo/assets/39889319/99057a71-2c25-4c9e-9d4b-15239d68e2f2">

I received an email from noreply@octo.app `Sign in to Octo`.

I clicked the "Sign in to Octo" link.

I was sent to a new tab at https://octo.app/__/auth/action?apiKey... where I saw a long error message displaying CSS rules, but no context I could find that would be particularly helpful to debug (error message seems to show the content of the expected page):

<img width="603" alt="Screenshot 2023-10-25 at 12 39 18 PM" src="https://github.com/davidmyersdev/octo/assets/39889319/c65bce9f-4eff-4b49-bef1-4150a641579e">

**Comment by davidmyersdev** [comment]
Hi @maggiehenry! Apologies for the delayed response, but would you mind sharing some info about your OS, browser, etc? Thanks so much!

**Comment by davidmyersdev** [comment]
It looks like this was due to a change made by Firebase. 🙃 This should be fixed now, but please let me know if you run into any more trouble!
