### ISSUE TITLE
How to run on dev machine?

### ISSUE THREAD

**Issue by raelb** [davidmyersdev/octo#260]
Hi,
Is it possible to give instructions on how to get the app running on a dev machine, for testing purposes?
Thanks

**Comment by davidmyersdev** [comment]
Hey @raelb. The [CONTRIBUTING.md](https://github.com/davidmyersdev/octo/blob/main/CONTRIBUTING.md) file should have what you need. If something is missing, would you mind letting me know here?

**Comment by raelb** [comment]
Thanks for the info.
