### ISSUE TITLE
sign in options are initially visible but then disappear

### ISSUE THREAD

**Issue by raelb** [davidmyersdev/octo#261]
I signed in previously (with email link). Now when I return to the app the follow error occurs:

https://github.com/davidmyersdev/octo/assets/13108198/b20f7a5d-d791-4816-9d16-65c799221f16

You will also notice, initially the app in in dark mode, then goes into light mode. (I have "Dark Reader" installed in FF, however, it is off now)

**Comment by davidmyersdev** [comment]
Thanks for opening this issue, @raelb!

**Comment by raelb** [comment]
I now get this error: (without clicking on sign in)

https://github.com/davidmyersdev/octo/assets/13108198/e89a678c-9b83-4601-9276-c7f772dcfe4d
